### ISSUE TITLE
Holding Locations Label

### ISSUE THREAD

**Issue by tampakis** [pulibrary/locations#38]
When I initially populated the holding locations table I made the label be a concatenation of the library name and collection name (Library: Collection). When we change library names (lets say from Library to Library1), the holding locations label keeps the old library name (Library: Collection). Maybe we want the holding location label field to actually only be the collection name (and concatenate the library and collection for json views)? One problem I already see with that is that some holding locations don't have collections, so I'd have to allow label to be empty for data validation.

**Comment by jpstroop** [comment]
Hmm...I think I'd assumed you would do the latter approach you explain above and not restate the library name in a HoldingLocation's label. Which model do you mean by "collection"? Library?

**Comment by tampakis** [comment]
Collection would be "Rare Books" in "Marquand Library: Rare Books"
It's what is called "collectionDisplay" on the other location service. There are a couple of holding locations codes that don't have a value for that so I should probably allow a blank value for that in the holding location model.

**Comment by tampakis** [comment]
Closed by #39
