### ISSUE TITLE
Change library codes to be consistent with Library web site

### ISSUE THREAD

**Issue by sdellis** [pulibrary/locations#68]
We would like to update the library codes so that they are consistent with the Library website.  The immediate use case is this: The Locations app will soon serve as the redirection point for the PULSearch "Where to find it" feature.  If an item is at a reserve location, we can improve the experience by providing a direct link to the library's reserves page for more information about how to get the item.  Most are consistent, and there are only two libraries that pose problems: http://library.princeton.edu/music ('mendel' in bibdata) and http://library.princeton.edu/plasma-physics ('plasma' in bibdata).  

@tampakis Do you see any potential side effects to changing these in bibdata?

**Comment by sdellis** [comment]
Alternatively, I suppose we could add a library website url field to the Library model that would allow us to provide the appropriate link.

**Comment by jpstroop** [comment]
@kevinreiss and @tampakis know the ins and outs of those codes better than
me at this point, but I'd hesitate to change any of them as all sorts of
policies are tied to them in other systems.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by sdellis** [comment]
Ok, thanks @jpstroop ... we can get this to work for the moment with redirects in Drupal.  And I'm glad to hear that this is being designed with the intent to work with other systems.  However, Drupal holds the most user-oriented, Library-specific data out of all of our systems, so I'm a bit surprised at the need for duplication here in locations/bibdata.

**Comment by jpstroop** [comment]
I think the codes from Voyager are more library-specific in terms of their
business cases, and we can't really control those anyway. Hence the
problem...

Maybe we should work (long term) on getting the codes out of Drupal so that
we can further limit the number of places where locations are managed. That
was one of the intentions of this app all along.

I think we already have codes for hours--how well do those map?

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by sdellis** [comment]
Doesn't seem like we're on the same page. The "codes" in locations/bibdata are identifiers for Libraries.  Does it make more sense for Drupal to pull Labels from BibData, or for BibData to pull "Labels" (and any other information it may need) from Drupal?  Either way, we need to make sure the code (or some id) is represented in both systems as _unique_ identifiers, so we can limit the number of places where locations are managed, correct?  I don't see how getting the codes out of Drupal would solve that.

Hours Locations seem to be a duplicated subset of Libraries.  I'm not sure why there is not simply a "has hours" boolean value for Libraries.  With the current approach, a Library and an Hours Location could have different codes. I can't speak to it as I don't really understand the decisions behind doing it that way.  @kevinreiss were you involved in the Hours Locations work?

**Comment by kevinreiss** [comment]
The codes are Drupal field values that give the branch calendar and library home pages can have "friendly" urls. They are same string value i.e. (music, plasma-physics, marquand) for both. The hours location value should also work fine for the token substitution you want for the redirect. I'd forgotten about it, use that.

**Comment by sdellis** [comment]
@kevinreiss but there is no relationship from Library to Hours Location, so there is no way for me to use it.  Again, it seems that Hours Location is redundant and can be simplified by folding it into Library, no?

**Comment by jpstroop** [comment]
Different locations in Firestone have different hours, right.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by kevinreiss** [comment]
There is a relationship between a location and and an hours location. You should have the location info so you get the data through that relationship. Bibdata may need some configuration so that every location does have this relationship set.

**Comment by sdellis** [comment]
@kevinreiss If there was a relationship, Hours Location should include a _WithLibrary_ concern [like Holding Location does](https://github.com/pulibrary/locations/blob/development/app/models/locations/holding_location.rb#L4), or at least a _belongs_to_, right?  What field is the association made on?

**Comment by kevinreiss** [comment]
https://github.com/pulibrary/locations/blob/development/app/models/locations/holding_location.rb#L6

**Comment by sdellis** [comment]
Duh. I think I'm getting tripped up by the different meanings of "locations, libraries, holding locations, hours locations", but now it's clear.  I will update the PR to use the Hours Location code value rather than the Library code value.

**Comment by sdellis** [comment]
Ok, so we are using redirects on the Drupal site to make this work. Unfortunately, three branch libraries do not mention reserves on their branch sites (marquand, eastasian and plasma). We should approach them about adding this content.
