### ISSUE TITLE
Unit tests will not run due to FriendlyId error

### ISSUE THREAD

**Issue by sdellis** [pulibrary/locations#73]
App runs fine via server, but tests fail due to the following error: 

`/locations/.internal_test_app/config/initializers/friendly_id.rb:12:in <top (required)>: uninitialized constant FriendlyId (NameError)`

**Comment by sdellis** [comment]
FYI - I have deleted and regnerated the test app

**Comment by jpstroop** [comment]
@sdellis I just cloned the repo and followed the README for generating the app and I'm not seeing that error when I run `rake spec`. Not sure what to say -- have you run `bundle install`? Are you using rvm? Maybe try a new gemset?

**Comment by kevinreiss** [comment]
@jpstroop are you not using RVM? I actually got the same error using a
fresh gemset with RVM. I wonder if upgrading to the latest engine_cart can
fix this. That has helped with similar issues in the past.

**Comment by jpstroop** [comment]
I am, and used a fresh gemset.
