### ISSUE TITLE
Move floors controller and model to a seperate branch

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/locations#82]
The floors controller and model are not currently used in production and introduce unnecessary dependencies that make installation of the marc_liberation app difficult (and it is already somewhat difficult). The floors image uploader uses CarrierWave::RMagick which requires the installation of an old version of ImageMagick (6.9) on the host machine. I propose that we move the floors logic from master and into a seperate branch to be further developed if the need arises.

**Comment by kevinreiss** [comment]
I think this is a good idea. This was a development effort that wound up being put on hold and I'm not sure when we'll come back to it.

**Comment by eliotjordan** [comment]
Floors moved into new branch: https://github.com/pulibrary/locations/tree/locations-floors-branch
